
export const metadata = {
  title: "Man Navlakha Project",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <main className="min-h-screen">
      {children}
    </main>
  );
}
